version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: tuki_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    env_file:
      - ./.env
    ports:
      - '5436:5432'

  app:
    container_name: tuki_api_app
    build: ./
    command: "./bin/rails server"
    env_file:
      - ./.env
    volumes:
      - app_storage:/rails/storage # add local code to dockerfile
    depends_on:
      - db  # add all dependant container
    ports:
      - "3000:3000"

volumes:
  postgres_data: {}
  app_storage: {}
