version: '3.7'
services:
  db:
    image: postgres:16.1-bullseye
    container_name: db.tuki_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - tuki_api

  app:
    image: app.tuki_api
    container_name: app.tuki_api
    build: ./
    command: "./bin/rails server"
    env_file:
      - ./.env
    volumes:
      - app_storage:/rails/storage # add local code to dockerfile
    depends_on:
      - db  # add all dependant container
    ports:
      - "3000:3000"
    networks:
      - tuki_api

volumes:
  postgres_data: {}
  app_storage: {}

# define the network, so that containers that reside on this same network can talk to each other
# via their `container_names`
networks:
  tuki_api:
    driver: bridge